/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mock;

import mock.better.BetterDAO;
import mock.db.IDBClient;
import mock.db.Person;
import mock.metrics.IMetrics;
import org.junit.Test;

import static org.junit.Assert.*;

public class BetterDAOTests {
    private static final String TEST_ID = "12345";
    private static final Person TEST_PERSON = new Person(TEST_ID, "John", "Smith", 45);

    @Test
    public void testAddPerson() {
        IDBClient db = new MockDBClient(TEST_ID, TEST_PERSON);
        IMetrics metrics = new MockMetrics();
        BetterDAO dao = new BetterDAO(db, metrics);

        String id = dao.addPerson(TEST_PERSON);
        assertEquals(TEST_ID, id);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testAddPersonThrowsException() {
        // Set up MockDBClient to throw an exception
        IDBClient db = new MockDBClient(TEST_ID, TEST_PERSON, new IllegalArgumentException("error"));
        IMetrics metrics = new MockMetrics();
        BetterDAO dao = new BetterDAO(db, metrics);

        dao.addPerson(TEST_PERSON);
    }

    @Test
    public void testUpdatePerson() {
        IDBClient db = new MockDBClient(TEST_ID, TEST_PERSON);
        IMetrics metrics = new MockMetrics();
        BetterDAO dao = new BetterDAO(db, metrics);

        String id = dao.updatePerson(TEST_ID, TEST_PERSON);
        assertEquals(TEST_ID, id);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testUpdatePersonThrowsException() {
        // Set up MockDBClient to throw an exception
        IDBClient db = new MockDBClient(TEST_ID, TEST_PERSON, new IllegalArgumentException("error"));
        IMetrics metrics = new MockMetrics();
        BetterDAO dao = new BetterDAO(db, metrics);

        dao.updatePerson(TEST_ID, TEST_PERSON);
    }
}
